### PR TITLE
Test against PG11 and Postgis 2.5

### PR DESCRIPTION
**Pull request by ethervoid**

### CODE REVIEW

**Comment by ethervoid** [comment]
Test with PG11 are passing. When we should merge this to master? @Algunenano @javitonino ?

**Comment by ethervoid** [comment]
retest this please

**Comment by ethervoid** [comment]
retest this please

**Comment by javitonino** [comment]
I think we should pass the PG version to the script as a parameter so we can do two runs in travis, one with PG10 and one with PG11, since we are going to be supporting both versions for some months.

**Comment by ethervoid** [comment]
Passing using pg10 and pg11

**Comment by dgaubert** [comment]
🚀

**Pull request merged**
