### PR TITLE
Passes buffer size calculation to SQL query

### PR DESCRIPTION
**Pull request by fdansv**
Fixes https://github.com/CartoDB/Windshaft/issues/439

@javisantana

### CODE REVIEW

**Comment by javisantana** [comment]
Looks good to me but I don't know if windshaft has cartodb-extension as requirement cc @rochoa

**Comment by fdansv** [comment]
We were already using `CDB_XYZ_Extent` so I'd assume so. Merging, as discussed offline!

**Comment by javisantana** [comment]
:es:

**Comment by rochoa** [comment]
We will have to do this properly because we are relying on cartodb-postgresql extension in order to get this quicker but we should stick to postgis functions and calculate extent and buffer as we do for torque.

**Pull request merged**
