### PR TITLE
Adds support for buffer-size CartoCSS Map property in geojson tiles

### LINKED ISSUE #422: Add support for buffer-size in geojson renderer
geojson tiles should support cartocss' buffer-size.

### PR DESCRIPTION
**Pull request by rochoa**
Closes #422

### CODE REVIEW

**Comment by rochoa** [comment]
cc @dgaubert

**Comment by dgaubert** [comment]
Apart from the usage of `eval`, I guess that is totally necessary, LGTM

**Comment by rochoa** [comment]
The method name is a bit unfortunate, but it's not the global `eval` thingy: https://github.com/CartoDB/carto/blob/176886f1ad4b66f74bd95fa24e59cb60df1962c4/lib/carto/renderer_js.js#L39-L43

**Comment by dgaubert** [comment]
OMG 😱 
Also `jshint` scares

👍 then!

**Pull request merged**
