### PR TITLE
Add option to enable JOHN RAMBO

### PR DESCRIPTION
**Pull request by christianbundy**
This PR adds an option to enable "JOHN RAMBO" (which is very important to my team's [workflow](http://xkcd.com/1172/)), which was removed in 4f905bc741e92762f9f239bfbaaac5668badcd4c.

giphy

**¡VIVA LA RAMBO!**

### CODE REVIEW

**Comment by christianbundy** [comment]
I also saw this in `test/acceptance/server.js`, so I made sure it returned an HTTP 404 instead.

``` javascript
// FIXME: shouldn't this be a 404 ?
```

**Comment by enam** [comment]
+1
giphy

**Comment by neale** [comment]
:+1: 



cc: @dean

**Comment by dean** [comment]
+1

**Comment by rochoa** [comment]
:laughing: Sorry I've been dragging this one! Because it makes me happy and proud of contributors submitting this kind of PR!

What about making the welcome message a configuration thing and defaulting to the `WELCOME_MSG` if message is not in config?

My other worry is modifying the status code to a 404 as some people may be relying on having a 200 for health checks and so.

**Comment by rochoa** [comment]
Oh... and the mandatory Rambo gif...

rambo-ametralladora-69265

**Comment by rochoa** [comment]
In #538 we decide to honor our old friend John Rambo and merge this into the old v0.x series of Windshaft.

**Pull request closed without merging**
