### PR TITLE
Change test tile

### PR DESCRIPTION
**Pull request by rafatower**
Change the tile used to test a map when first requested so that we don't
use that level of zoom nor just a corner of the raster (literaly do not
use a "corner case").

@rochoa please review

### CODE REVIEW

**Comment by rochoa** [comment]
ping

**Comment by javisantana** [comment]
yes, I'd not do this, we could be fetching million points (not likely but ok)

**Comment by lbosque** [comment]
Probably because zoom 0 can be very expensive if there are million of points

**Comment by rafatower** [comment]
From what I saw, using `z = 30` was failing silently in many cases so I'd prefer to remove it at all if we do not find any actual quick test that could be useful

**Comment by rochoa** [comment]
Sorry but what do you mean by "using z = 30 was failing silently in many cases"? :confused:

**Comment by rafatower** [comment]
Due to the bug described [here](https://github.com/mapnik/mapnik/pull/2615) (btw a failing PR, my bad) in many cases the tile requested ended up in not rendering anything because of an int overflow. So a quick test that did not test anything... or else it should have failed.

**Comment by rochoa** [comment]
If the test fails the layergroup creation should fail otherwise we have a bug :-). At least we have relied on it for mapnik vectorial data until now.

**Comment by rochoa** [comment]
After discussing with @rafatower and @javisantana we are gonna test different zoom levels for raster and vector data.

**Comment by rafatower** [comment]
I'm having trouble with this again https://github.com/CartoDB/Windshaft/blob/277fa1a4868a84f03049541d0245dac57a001246/lib/windshaft/backends/map_validator.js#L105

**Comment by rafatower** [comment]
Quite old, closing this for the moment. Let's reopen if ever needed.

**Pull request closed without merging**
