### PR TITLE
Replace istanbul by nyc as code coverage tool

### PR DESCRIPTION
**Pull request by dgaubert**

### CODE REVIEW

**Comment by Algunenano** [comment]
jshint is complaning about I'm not sure what since `
/srv/test/results/compare-lib/js/coveringBad.js` doesn't make sense to me.

**Comment by dgaubert** [comment]
🤔 
https://github.com/CartoDB/Windshaft/commit/53a4b315bcbd9b94bfd77ba631b3d7ae07edb42f

**Comment by dgaubert** [comment]
I didn't use it before. I even did NOT aware of that. I guess we can remove it as it's a tool to see pixel diff when tests fail

**Comment by Algunenano** [comment]
:fire: We can always recover it in the future if the need it (and remember it existed at some point).

**Comment by dgaubert** [comment]
I'll do it in a separate PR, do you agree?

**Comment by dgaubert** [comment]
https://github.com/CartoDB/Windshaft/issues/717

**Comment by Algunenano** [comment]
All good

**Pull request merged**
