### PR TITLE
Torque tests: Sort objects before deep comparison

### PR DESCRIPTION
**Pull request by Algunenano**
Since the order of the torque results isn't guaranteed depending on how the query is handled by PostgreSQL we had some failing tests with PG9.6+. This PR takes care of it by ordering the objects in the tests before checking if they are equal

Tested locally with pg10. @jgoizueta Can you have a look and test if it's fixed for you too, please?

Fixes https://github.com/CartoDB/Windshaft/issues/574

### CODE REVIEW

**Comment by dgaubert** [comment]
Hey @Algunenano, thank you so much for taking care of this issue.

The point here is that we need to know if Postgres-9.6 will break current torque visualizations. We need to create a torque layer in Builder against Postgres 9.5 and another one against 9.6 and check if there are differences.

If help is needed, let me know!

**Comment by Algunenano** [comment]
So, here are my findings:
* To get the data from a provider, torque calls [getTileData](https://github.com/CartoDB/torque/blob/5d9b02a6da2c3b458fa4d60630a529b45bc5030b/lib/torque/provider/tilejson.js#L221) which calls _getTileData which is the one that does the GET and calls proccessTile before returning it. I'm using tilejson provider here but it's the same for the windshaft provider.
* The important function here is [processTile](https://github.com/CartoDB/torque/blob/5d9b02a6da2c3b458fa4d60630a529b45bc5030b/lib/torque/provider/tilejson.js#L51) which gets the rows received from the network and transforms it into a more efficient structure:
  * Checks all used dates and creates and array to hold values.
  * For each row in the received file:
    * For each date used:
       * If `!this.options.cumulative`: Adds this value to the date array (as a new node to a list).
       * If not (that is, using cumulative):  Adds an accumulated value to the date array (as a new node to a list)
  * Gathers all the results per slot in the date array and returns them as renderData and renderDataPos arrays.

Bonus: There is a bug in the [function](https://github.com/CartoDB/torque/blob/5d9b02a6da2c3b458fa4d60630a529b45bc5030b/lib/torque/provider/windshaft.js#L116) as it cannot be `this.options.cumulative` because 2 lines above it check for the opposite.

And here is when the rendering takes part and where to look depends on what you are rendering. For example for points it will end up calling [_renderTile](https://github.com/CartoDB/torque/blob/5d9b02a6da2c3b458fa4d60630a529b45bc5030b/lib/torque/renderer/point.js#L312) which will generate sprites with `generateSprite` and here it starts calling cartocss and canvas functions I don't know nothing about so I don't know if they are order independent or not. What's for sure is I haven't found anything anywhere enforcing order so, even if they where dependent on it, I don't know which order would be correct.

**Comment by Algunenano** [comment]
Based on @rochoa Torque renderer test I've added another commit to prove that you get the same output independently of the order of the data, so there is no difference between PG 9.5 and PG10.

**Comment by Algunenano** [comment]
Making sure the NEWs comment ends up in the current release. I'll merge if test are Ok.

**Pull request merged**
